name: SonarQube Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  sonarQubeScan:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SonarQube Scanner
        uses: sonarsource/sonarqube-scan-action@master
        with:
          sonar-project-key:sonar.projectKey=SAST
          sonar-host-url: http:localhost:9000
          sonar-token: ${{ secrets.SONARQUBE_TOKEN }}

      - name: Run SonarQube Scan
        run: sonar-scanner
